### PR TITLE
allow configuration of AWS-S3 as the static file service

### PR DESCRIPTION
**Pull request by lbiedinger**

### CODE REVIEW

**Comment by dennisvdvliet** [comment]
@lbiedinger I might have mentioned this to you already during our skype call but there is a difference in the way remote urls are generated by swift vs s3

Compare https://github.com/europeana/dragonfly-swift-data-store/blob/develop/lib/dragonfly/swift_data_store.rb#L61 to https://github.com/markevans/dragonfly-s3_data_store/blob/master/lib/dragonfly/s3_data_store.rb#L74

Swift always makes an API call while with S3 you can also build the url without making a call to S3

**Comment by lbiedinger** [comment]
@dennisvdvliet is this all internal to the respective dragonfly datastore gem though? Is there any point where we could save on an API call from within the Exhibitions app?

**Comment by dennisvdvliet** [comment]
@lbiedinger Don't think so, just make sure not to use an expires_at when using s3 since that would trigger a call to the s3 api (see dragonfly s3 gem).

**Comment by rwd** [comment]
@lbiedinger could you ensure that the `expires_at` calls, e.g. https://github.com/europeana/europeana-virtual-exhibitions/blob/develop/app/controllers/alchemy/pictures_controller.rb#L13, are only run if the data store is Swift?

**Pull request merged**
